version: "3.9"

services:

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_HOST_IP}:${FRONTEND_HOST_PORT}:5000"
    command: sh -c "yarn build && yarn serve -s -n build"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
