version: "3.9"

services:
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${DB_HOST_IP}:${DB_HOST_PORT}:5432"

  backend:
    build: ./backend
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - BACKEND_HOST_PORT
    env_file:
      - backend-variables.env
    ports:
      - "${BACKEND_HOST_IP}:${BACKEND_HOST_PORT}:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_HOST_IP}:${FRONTEND_HOST_PORT}:5000"
    command: sh -c "yarn build && yarn serve -s -n build"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
