version: "3.9"

services:
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${DB_HOST_IP}:${DB_HOST_PORT}:5432"

  backend:
    build: ./backend
    environment:
      - DOMAIN
      - BACKEND_HOST_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file:
      - backend-variables.env
    ports:
      - "${BACKEND_HOST_IP}:${BACKEND_HOST_PORT}:8000"
    command: sh -c "wait-for db:5432 -- gunicorn sp_django.wsgi -b 127.0.0.1:8001"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_DOMAIN=${DOMAIN}
      - REACT_APP_BACKEND_PORT=${BACKEND_HOST_PORT}
    ports:
      - "${FRONTEND_HOST_IP}:${FRONTEND_HOST_PORT}:5000"
    command: sh -c "yarn build && yarn serve -s -n build"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
